### ISSUE TITLE
Missing Oracle text on Wastes

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#245] opened 2016-11-07 19:49 UTC
Wastes have the following Oracle text:

```
{T}: Add {C} to your mana pool.
```

For some reason, this is missing in MTG JSON.

**Comment by thg2k** [comment] 2016-12-20 21:18
That depends, if you refer to the current Oracle text in the gatherer yes, but the printed version just like other basic lands has only the big symbol of the mana printed, so I think it's more a bug in the gatherer rather than a bug in json, imho.

**Comment by fenhl** [comment] 2016-12-20 21:20
It's not a bug in Gatherer. Wastes has the Oracle text with the mana ability so that it can be tapped for mana.

**Comment by lsmoura** [comment] 2017-01-19 12:33
mtgjson, by design, has no text on any **Basic Land** cards. It's removed while it's fetched.

**Comment by fenhl** [comment] 2017-01-19 12:39
Then there should be a special case for Wastes.

**Comment by lsmoura** [comment] 2017-01-19 12:53
Ok... Why?

I actually believe gatherer is wrong. If the oracle text on a [Forest](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423576) is just "F", why does the text on [Wastes](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=false&multiverseid=407693) should be "{T}: Add {C} to your mana pool."?

**Comment by fenhl** [comment] 2017-01-19 13:13
Forest has the basic land type Forest. This means that [rule 305.6](http://mtgsalvation.gamepedia.com/Land#Rules) grants it the _intrinsic mana ability_ “{T}: Add {G} to your mana pool.” The F in the Oracle text is supposed to be a representation of the big mana symbol, which is a watermark that has no rules meaning.

Wastes has no basic land type, so it doesn't have any intrinsic mana abilities, so the Oracle text needs to spell out the mana ability. The reason this ability is not on the printed card is to make the card visually consistent with the other basic lands, but from a rules perspective it's more confusing than helpful since this only works because Oracle text takes precedence.

**Comment by lsmoura** [comment] 2017-01-19 13:17
WTF!? They haven't updated the rules for Wastes?? :man_facepalming:

I'm marking this as a bug. If you want to contribute with a change on OGW.json to the r_3-8-1 branch, you're welcome to (and I'd appreciate it).

**Comment by dgant** [comment] 2017-01-19 13:18
I think the distinction is that Wastes is a basic land, with the subtype "Wastes", but "Wastes" is not a basic land type, so the card needs the next.

**Comment by lsmoura** [comment] 2017-01-19 13:19
@dgant I understant that now. What I don't understand is, why does the card has "Basic Land" written on it and they haven't updated the rules?

**Comment by fenhl** [comment] 2017-01-19 13:20
Wastes does not have any subtypes. This was an intentional design decision to avoid upsetting the balance of things like domain.

**Comment by dgant** [comment] 2017-01-19 13:23
@fenhl Oh, you're entirely right. I falsely remembered it as having a subtype.

**Comment by fenhl** [comment] 2017-01-19 13:38
I don't know how to fix this. It would be great if someone else could try.

**Closed** 2017-01-23 12:34 UTC
Labels: bug
