### ISSUE TITLE
Duplicate Record

### ISSUE THREAD

**Issue by stevenjamesfrank** [mtgjson/mtgjson#468] opened 2017-09-26 12:32 UTC
The AllSetsArray.json file has (at least) one duplicate card (by Id):

      {
        "artist": "Tsutomu Kawade",
        "cmc": 3,
        "colorIdentity": [
          "U"
        ],
        "colors": [
          "Blue"
        ],
        "id": "2ba1628b4169e33a4a6773124bec72fadfb6c983",
        "imageName": "jaraku the interloper",
        "layout": "flip",
        "manaCost": "{1}{U}{U}",
        "mciNumber": "31b",
        "multiverseid": 74489,
        "name": "Jaraku the Interloper",
        "names": [
          "Callow Jushi",
          "Jaraku the Interloper"
        ],
        "number": "31b",
        "power": "3",
        "rarity": "Uncommon",
        "subtypes": [
          "Spirit"
        ],
        "supertypes": [
          "Legendary"
        ],
        "text": "Remove a ki counter from Jaraku the Interloper: Counter target spell unless its controller pays {2}.",
        "toughness": "4",
        "type": "Legendary Creature — Spirit",
        "types": [
          "Creature"
        ]
      },
      {
        "artist": "Tsutomu Kawade",
        "cmc": 3,
        "colorIdentity": [
          "U"
        ],
        "colors": [
          "Blue"
        ],
        "id": "2ba1628b4169e33a4a6773124bec72fadfb6c983",
        "imageName": "jaraku the interloper",
        "layout": "flip",
        "manaCost": "{1}{U}{U}",
        "mciNumber": "31b",
        "multiverseid": 74489,
        "name": "Jaraku the Interloper",
        "names": [
          "Callow Jushi",
          "Jaraku the Interloper"
        ],
        "number": "31b",
        "power": "3",
        "rarity": "Uncommon",
        "subtypes": [
          "Spirit"
        ],
        "supertypes": [
          "Legendary"
        ],
        "text": "Remove a ki counter from Jaraku the Interloper: Counter target spell unless its controller pays {2}.",
        "toughness": "4",
        "type": "Legendary Creature — Spirit",
        "types": [
          "Creature"
        ]
      },

**Comment by fenhl** [comment] 2017-09-26 12:56
Closing as duplicate of #388.

**Closed by fenhl** 2017-09-26 12:56 UTC
