### ISSUE TITLE
Back face of Magic Origins creaturewalkers missing from Prerelease Events set

### ISSUE THREAD

**Issue by Palladinium** [mtgjson/mtgjson#280] opened 2017-01-25 01:15 UTC
In both Magic Origins (`ORI`) and the Prerelease Events sets (`pPRE`), each of the five double-faced creature/planeswalker cards has a card with a `names` field indicating its front and back face.

However, the back faces of those cards are missing from the `pPRE` set, and are only present in `ORI`.

The affected cards are as follows:

Front face | Back face
------|------
Chandra, Fire of Kaladesh | Chandra, Roaring Flame
Jace, Vryn's Prodigy | Jace, Telepath Unbound
Kytheon, Hero of Akros | Gideon, Battle-Forged
Liliana, Heretical Healer | Liliana, Defiant Necromancer
Nissa, Vastwood Seer | Nissa, Sage Animist

**Comment by fenhl** [comment] 2017-08-17 13:23
Closing as duplicate of #423, which has additional discussion.

**Closed by fenhl** 2017-08-17 13:23 UTC
Labels: duplicate
