### ISSUE TITLE
Some missing/incorrect Artists

### ISSUE THREAD

**Issue by jceddy** [mtgjson/mtgjson#210] opened 2016-08-29 16:17 UTC
Prerelease Promo version of Nissa, Vastwood Seer artist should be Wesley Burt.
Media Inserts version of Pia and Kiran Nalaar artist should be Tyler Jacobson.
Media Inserts version of Kothophed, Soul Hoarder artist should be Tianhua X.
Media Inserts version of Hixus, Prison Warden artist should be Magali Villeneuve.
Media Inserts version of Dwynen, Gilt-Leaf Daen artist should be Steven Belledin.
Media Inserts version of Alhammarret, High Arbiter artist should be Richard Wright.

**Comment by lsmoura** [comment] 2016-08-29 17:19
Can I have some reference on this info?

**Comment by jceddy** [comment] 2016-09-12 14:41
I just looked at the text on the cards. Do I need another reference?

**Comment by jceddy** [comment] 2016-09-12 14:45
For Nissa, Vastwood Seer prerelease promo, Star City Games has a good scan where you can read the artist name. For the other five, you just need to look at the front of the Origins Intro Deck packaging. It seems these missing/incorrect artists names are from magiccards.info, and a lot of those scans are blurry. I  wanted to get it corrected there (at the source), but can't find any reliable contact information for that site.

**Comment by jceddy** [comment] 2016-09-12 14:54
Pia and Kiran Nalaar: http://www.tylerjacobsonart.com/store/pia-and-kiran-nalaar-artists-proof
Kothophed, Soul Hoarder: http://www.atomicempire.com/singleslist.aspx?sz=50&pics=n&sort=1&idnt=16298&inst=36288&incfoil=y&

For Hixus, Prison Warden, I can actually read the name on the scan there, but it is helpful that I also looked at the physical card. Ditto the rest of them.

**Comment by fenhl** [comment] 2017-08-17 10:47
Closing as duplicate of #319 since that issue has a link to the card images.

**Closed by fenhl** 2017-08-17 10:47 UTC
Labels: duplicate
