### ISSUE TITLE
Two cards from Betrayers of Kamigawa are duplicated

### ISSUE THREAD

**Issue by pbaranay** [mtgjson/mtgjson#441] opened 2017-08-15 22:04 UTC
Scarmaker and Jaraku the Interloper, both from *Betrayers of Kamigawa*, are duplicated in the JSON data. Notably, both of these are flip cards, although they are not _each other's_ flip card.

In each case, one instance has the correct data, but the other has the `originalType` and `originalText` of its lower flip part (Hired Muscle and Callow Jushi, respectively).

**Comment by fenhl** [comment] 2017-08-15 22:08
Closing as duplicate of #388.

**Closed by fenhl** 2017-08-15 22:08 UTC
Labels: duplicate

**Comment by pbaranay** [comment] 2017-08-15 22:12
@fenhl Thanks for the quick response! Sorry, didn't think to check for dupes.
