### ISSUE TITLE
MagicCards.info comparison fails on Æ cards.

### ISSUE THREAD

**Issue by gwax** [mtgjson/mtgjson#395] opened 2017-07-13 06:18 UTC
Sentences in card titles that start with Æ were replaced with Ae by WotC but MagicCards.info hasn't caught up. Then we get a bunch of does not match errors.

**Comment by ZeldaZach** [comment] 2017-07-13 06:31
Can we catch them in a regex/replace?

**Comment by bakert** [comment] 2017-07-13 22:48
Duplicate of, or related to, #304

**Comment by ZeldaZach** [comment] 2017-07-13 23:04
Dupe #304

**Closed by ZeldaZach** 2017-07-13 23:04 UTC
