### ISSUE TITLE
Incorrect(?) set code for DDA: Garruk vs. Liliana

### ISSUE THREAD

**Issue by csuhta** [mtgjson/mtgjson#212] opened 2016-09-04 00:49 UTC
The Gatherer set code for Duel Decks Anthology: Garruk vs. Liliana is (ugh) `DD3_GVL`, but the actual cards have `GVL` printed on them.

You have `dd3_gvl` for both the MTGJSON set code and the Gatherer code. Should MTGJSON have the printed code set for the `code` property, and the `dd3_gvl` for the `gathererCode` property?

![](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=393880&type=card)

**Comment by gwax** [comment] 2017-07-23 06:21
Duplicate of #182

**Closed by gwax** 2017-07-23 06:21 UTC

**Comment by fenhl** [comment] 2017-07-23 09:42
To elaborate on this, we cannot use the set codes printed on the card frame for _Duel Decks Anthology_, since they would cause a collision with _Duel Decks: Elves vs. Goblins_, which has the set code EVG.
