### ISSUE TITLE
Split cards are broken

### ISSUE THREAD

**Issue by mirandir** [mtgjson/mtgjson#359] opened 2017-06-13 18:37 UTC
Hello,

It seems split cards are broken. The second-half of the card is mostly a copy of the first one.
Example: Bound / Determined in DIS.

Maybe related to the mass rebuild in https://github.com/mtgjson/mtgjson/pull/328.

Not sure about flip / double-faced cards.

**Comment by fenhl** [comment] 2017-07-11 03:58
Closing as duplicate of #375, which has more info and activity.

**Closed by fenhl** 2017-07-11 03:58 UTC
