### ISSUE TITLE
Nissa, Steward of Elements has a loyalty of null

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#517] opened 2017-12-16 19:03 UTC
Nissa, Steward of Elements is the only planeswalker with a non-numeric loyalty- it's X, defined in the mana cost. This seems to have caused a problem building the file, becuase it now displays as having a value for loyalty, but that value is null.

Suggested fix: Change the loyalty field from a number to a string, and then X can be properly represented as "X". This brings loyalty in line with power and toughness, which are also strings to account for cards like Tarmogoyf.

**Comment by fenhl** [comment] 2017-12-17 11:07
Closing as duplicate of #320.

**Closed by fenhl** 2017-12-17 11:07 UTC
Labels: duplicate
