### ISSUE TITLE
uuid to mcmId far from always correct on special cards

### ISSUE THREAD

**Issue by billylarsson** [mtgjson/mtgjson#624] opened 2020-07-14 20:28 UTC
#### Version(s) affected
- [x] MTGJSON 4
- [x] MTGJSON 5

#### Description of Bug

copy/paste from discord:

i think you got some (those i checked) cards with Flavor names wrongly connected from cardmarkets prices in AllPrices.
example: 6f8ddb82-805d-573a-beca-5d8f369c8108

The human eye knows that uuid: 6f8ddb82-805d-573a-beca-5d8f369c8108 should be mcmId: 451838 and not 451828 (as currently inputed)

approach:

Firstly I download the cardmarket’s expansion and cards data. 
"GET", "https://api.cardmarket.com/ws/v2.0/output.json/games/1/expansions"
"GET", f"https://api.cardmarket.com/ws/v2.0/output.json{endLink}"
I store them locally for further and reuse and expand if something new comes up (its currently like 50mb or so for everything)

Then from that data I fill out the blanks in MTGJson sets, mcmId and mcmName. (There’s more blanks in V5 than V4).

Next in MTGJson cards I set  mcmId’s to “NULL” because many of them are wrong . (I only find its useful to choose the post-pioneer cards)

Then since everyone is null, I take the easy ones first.
if setCode == setCode and cardNumber == cardNumer: ; update MTGJson/cards/mcmId with the one from MCM’s databank.
Next I match cardNumber -s-ending and cardNumber -p-ending and use isFoilOnly == True to the MCM prereleasepromo, also those are sometimes separable from using release-date since the prereleasepromo are sometimes dated earlier.
After positioning say three cards with the same name with highest possible accuracy out of four candidates, if both MTGJson and MCM-databank has four of that card means that the only card remaining from both databases may very well be a good match, like playing Sudoku.

If one are to look at row 318 in AllPrintings/sets it is clear that “PIKO” hasn't any mcmId or mcmName, I would assume if I were to debug the issue with the knowledge of your code that I would start there, perhaps that's connected to why many of the Ikoria cards are mismatched or left without an mcmId or even sharing the same mcmId while still being different at both ends.
A guess why the setCodes/names are'nt matched can be because cardmarket use a different naming, thay have two : colons while "you" just have one.

`
if set_name.lower() in self.set_map.keys():
            return str(self.set_map[set_name.lower()]["mcmName"])
`

the snippet above may be part of the problem, spontaneously i would think of trying something like set_name.replace(":","") to get the set_names from MTGJson and cardmarket connect to each others.

**Comment by JosephSBoyle** [comment] 2020-07-31 13:46
I've compiled a list of sets where uuid's don't map to mcmIDs, upon a quick inspection it seems to be almost exlusively _promotional_ sets affected by this issue. The only exceptions I can see are Double Horizons and Modern Horizons. 

[affected_sets.txt](https://github.com/mtgjson/mtgjson/files/5007313/affected_sets.txt)

**Comment by billylarsson** [comment] 2020-08-13 13:17
My solution: https://pastebin.com/eb2qCtmg

**Comment by ZeldaZach** [comment] 2020-09-10 22:52
Sorry for the long delay on responding. I want to solve this, just it's a bigger issue than I realized. Will try to come up with ways to handle the API, or have a cleaner approach soon

**Comment by ZeldaZach** [comment] 2020-09-27 01:47
Note for self: https://github.com/mtgjson/mtgjson/blob/master/mtgjson5/providers/cardmarket.py#L209 this is _super wrong_ and can be fixed by better hashing the content

**Comment by Samurus** [comment] 2021-05-27 07:38
linked issue: https://github.com/mtgjson/mtgjson/issues/798
I also commented some of my insights. 
How is the progress? Whats the best way to help here?

**Comment by ZeldaZach** [comment] 2022-12-21 16:34
I've gone through and confirmed this should be addressed across the board now. If you run across ancillary issues, please feel free to comment or cut a new ticket!

**Closed as completed by ZeldaZach** 2022-12-21 16:34 UTC
Labels: Data Issue, Help Wanted, MTGJSON v5
