### ISSUE TITLE
layout and names incorrect for Zndrsplt, Eye of Wisdom and Okaun, Eye of Chaos

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#613] opened 2018-08-29 09:49 UTC
Both have layout=flip incorrectly (probably because the rules text contains "flip a coin").

The order of names is wrong in that it is not consistent across both entries. For Zndrsplt's entry Okaun is listed first. And *vice versa*.

**Comment by fenhl** [comment] 2018-08-29 09:52
Duplicate of #588 (layout) and #586 (names).

**Closed by fenhl** 2018-08-29 09:52 UTC

**Comment by bakert** [comment] 2018-08-29 10:01
Oops, thanks.
