### ISSUE TITLE
Crawler seems not to fetch translations from 2nd and further pages 

### ISSUE THREAD

**Issue by makhotkin** [mtgjson/mtgjson#473] opened 2017-10-12 11:18 UTC
Let's look at card Forest#249 (fullart) from ZEN as it's displayed in ZEN-x.json file
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=195183
There are only 25 translations under foreignNames property: 8 for German, 8 for Spanish, 8 for Italian and one for French, though we all know that there have to be more Forests. This perfectly matches the 25 results shown in page http://gatherer.wizards.com/Pages/Card/Languages.aspx?page=0&multiverseid=195183 where one can see pagination links that the crawler seems not to follow.

Same is true for basic lands from other editions. For example forests from AKH are missing Russian, Chinese and Spanish translation due to the same issue.

Please consider fixing that.

**Comment by tooomm** [comment] 2017-10-12 11:57
Duplicate of #144

**Closed** 2017-10-12 12:57 UTC
Labels: duplicate
