### ISSUE TITLE
Jaraku the Interloper and Scarmaker have two identical objects in json

### ISSUE THREAD

**Issue by petejohnson84** [mtgjson/mtgjson#388] opened 2017-07-11 03:30 UTC
When importing into a mysql database with unique key on sha1 field, I notice that there are two duplicate objects having same sha1. The first is Jaraku the Interloper (2ba1628b4169e33a4a6773124bec72fadfb6c983) and the second is Scarmaker (34bbf9e14b771f9eb4c4c2970ed54b8ff836118a). These are the only two objects that appear to have a duplicate object in the data set.

**Comment by fenhl** [comment] 2017-07-11 03:45
This is the same bug as #240, which was fixed in 474c0c0. However, it seems that this was done by patching the JSON files manually, so the next rebuild of these sets broke it again. To properly fix this, we need to add the fixes to shared/C.js.

**Comment by ZeldaZach** [comment] 2017-07-11 03:48
Can you work on that fix @fenhl ?

**Comment by fenhl** [comment] 2017-07-11 03:50
Not until tomorrow at the earliest.

**Comment by fenhl** [comment] 2017-07-11 03:51
I'll assign myself so I don't forget, but if anyone else wants to apply the patch before I have time, feel free to do so.

**Comment by fenhl** [comment] 2017-09-09 18:37
I won't have time to fix this any time soon. Someone else might want to try.

**Comment by Hologos** [comment] 2017-09-11 18:17
Hello, guys. I just came across the same problem. I found more duplicated thought.

```
Cannot insert card 'Jaraku the Interloper' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Chisei, Heart of Oceans' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Disrupting Shoal' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Floodbringer' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Genju of the Falls' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Heed the Mists' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Higure, the Still Wind' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Jetting Glasskite' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Kaijin of the Vanishing Touch' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Kira, Great Glass-Spinner' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Minamo Sightbender' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Minamo's Meddling' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Mistblade Shinobi' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ninja of the Deep Hours' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Patron of the Moon' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Phantom Wings' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Quash' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Quillmane Baku' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Reduce to Dreams' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ribbons of the Reikai' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Shimmering Glasskite' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Soratami Mindsweeper' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Stream of Consciousness' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Sway of the Stars' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Teardrop Kami' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Threads of Disloyalty' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Toils of Night and Day' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Tomorrow, Azami's Familiar' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Veil of Secrecy' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Walker of Secret Ways' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Bile Urchin' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Blessing of Leeches' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Call for Blood' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Crawling Filth' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Eradicate' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Genju of the Fens' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Goryo's Vengeance' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Hero's Demise' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Hired Muscle' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Scarmaker' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Scarmaker' due to Duplicate entry '34bbf9e14b771f9eb4c4c2970ed54b8ff836118a' for key 'PRIMARY'
Cannot insert card 'Horobi's Whisper' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ink-Eyes, Servant of Oni' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Kyoki, Sanity's Eclipse' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Mark of the Oni' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Nezumi Shadow-Watcher' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ogre Marauder' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Okiba-Gang Shinobi' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Patron of the Nezumi' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Psychic Spear' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Pus Kami' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Scourge of Numai' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Shirei, Shizo's Caretaker' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Sickening Shoal' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Skullmane Baku' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Skullsnatcher' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Stir the Grave' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Takenuma Bleeder' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Three Tragedies' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Throat Slitter' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Toshiro Umezawa' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Yukora, the Prisoner' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Akki Blizzard-Herder' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Akki Raider' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ashen Monstrosity' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Aura Barbs' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Blademane Baku' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Blazing Shoal' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Clash of Realities' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Crack the Earth' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Cunning Bandit' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Azamuki, Treachery Incarnate' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'First Volley' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Flames of the Blood Hand' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Frost Ogre' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Frostling' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Fumiko the Lowblood' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Genju of the Spires' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Goblin Cohort' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Heartless Hidetsugu' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'In the Web of War' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ire of Kaminari' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ishi-Ishi, Akki Crackshot' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Kumano's Blessing' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Mannichi, the Fevered Dream' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ogre Recluse' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Overblaze' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Patron of the Akki' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ronin Cliffrider' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Shinka Gatekeeper' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Sowing Salt' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Torrent of Stone' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Twist Allegiance' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Body of Jukai' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Budoka Pupil' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ichiga, Who Topples Oaks' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Child of Thorns' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Enshrined Memories' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Forked-Branch Garami' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Genju of the Cedars' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Gnarled Mass' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Harbinger of Spring' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Isao, Enlightened Bushi' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Iwamori of the Open Fist' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Kodama of the Center Tree' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Lifegift' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Lifespinner' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Loam Dweller' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Mark of Sakiko' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Matsu-Tribe Sniper' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Nourishing Shoal' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Patron of the Orochi' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Petalmane Baku' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Roar of Jukai' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Sakiko, Mother of Summer' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Sakura-Tribe Springcaller' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Scaled Hulk' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Shizuko, Caller of Autumn' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Sosuke's Summons' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Splinter' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Traproot Kami' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Unchecked Growth' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Uproot' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Vital Surge' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Genju of the Realm' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Baku Altar' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Blinding Powder' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Mirror Gallery' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Neko-Te' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Orb of Dreams' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ornate Kanzashi' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Ronin Warclub' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Shuko' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Shuriken' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Slumbering Tora' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'That Which Was Taken' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Umezawa's Jitte' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Gods' Eye, Gate to the Reikai' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Tendo Ice Bridge' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
```

**Comment by fenhl** [comment] 2017-09-11 19:40
@Hologos: Cannot reproduce. I searched [BOK.json](https://github.com/mtgjson/mtgjson/blob/master/json/BOK.json) for `"name": "Disrupting Shoal"` and only found 1 result.

**Comment by Hologos** [comment] 2017-09-12 08:14
@fenhl: It's visible in AllSets.json 3.11.5 I downloaded yesterday from the website.

```
...
{
        "artist": "Tsutomu Kawade",
        "cmc": 3,
        "colorIdentity": [
          "U"
        ],
        "colors": [
          "Blue"
        ],
        "id": "2ba1628b4169e33a4a6773124bec72fadfb6c983",
        "imageName": "jaraku the interloper",
        "layout": "flip",
        "manaCost": "{1}{U}{U}",
        "mciNumber": "31b",
        "multiverseid": 74489,
        "name": "Jaraku the Interloper",
        "names": [
          "Callow Jushi",
          "Jaraku the Interloper"
        ],
        "number": "31b",
        "power": "3",
        "rarity": "Uncommon",
        "subtypes": [
          "Spirit"
        ],
        "supertypes": [
          "Legendary"
        ],
        "text": "Remove a ki counter from Jaraku the Interloper: Counter target spell unless its controller pays {2}.",
        "toughness": "4",
        "type": "Legendary Creature — Spirit",
        "types": [
          "Creature"
        ]
      },
      {
        "artist": "Tsutomu Kawade",
        "cmc": 3,
        "colorIdentity": [
          "U"
        ],
        "colors": [
          "Blue"
        ],
        "id": "2ba1628b4169e33a4a6773124bec72fadfb6c983",
        "imageName": "jaraku the interloper",
        "layout": "flip",
        "manaCost": "{1}{U}{U}",
        "mciNumber": "31b",
        "multiverseid": 74489,
        "name": "Jaraku the Interloper",
        "names": [
          "Callow Jushi",
          "Jaraku the Interloper"
        ],
        "number": "31b",
        "power": "3",
        "rarity": "Uncommon",
        "subtypes": [
          "Spirit"
        ],
        "supertypes": [
          "Legendary"
        ],
        "text": "Remove a ki counter from Jaraku the Interloper: Counter target spell unless its controller pays {2}.",
        "toughness": "4",
        "type": "Legendary Creature — Spirit",
        "types": [
          "Creature"
        ]
      },
...
```

**Comment by Hologos** [comment] 2017-09-12 09:09
@fenhl: You are correct. There is an issue with ORM framework I use, it tries to save the duplicite entity everytime I try to persist another entity with the same type.

Now the output is only:
```
_____ DELETE _____

_____ INSERT _____

Loading JSON file.
Set 'Betrayers of Kamigawa' was saved.
Cannot insert card 'Jaraku the Interloper' due to Duplicate entry '2ba1628b4169e33a4a6773124bec72fadfb6c983' for key 'PRIMARY'
Cannot insert card 'Scarmaker' due to Duplicate entry '34bbf9e14b771f9eb4c4c2970ed54b8ff836118a' for key 'PRIMARY'
Everything done.
```

So nothing new. :-)

**Comment by fenhl** [comment] 2017-10-29 00:31
I may or may not have a fix on [my flip branch](https://github.com/fenhl/mtgjson/tree/flip), waiting for #477 to be merged so I can see if it works.

**Comment by fenhl** [comment] 2017-10-30 19:02
Now running into this error while rebuilding on my branch, any ideas?

```
3ED:de
Processing 306 cards
TypeError: Cannot read property 'length' of undefined
    at CBRunner.fun (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:124:34)
    at CBRunner.CBRunner.run (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:929:8)
    at CBIterator.CBIterator.next (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:963:18)
    at CBIterator.CBIterator.go (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:948:8)
    at Array.serialForEach (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:986:34)
    at Function.getMultiverses (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:121:14)
    at next (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:51:22)
    at tiptoe (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:114:2)
    at retrieve (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:119:2)
    at /opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:104:3
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:21
                                throw args[0];
                                ^

TypeError: Cannot read property 'length' of undefined
    at CBRunner.fun (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:124:34)
    at CBRunner.CBRunner.run (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:929:8)
    at CBIterator.CBIterator.next (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:963:18)
    at CBIterator.CBIterator.go (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:948:8)
    at Array.serialForEach (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/@sembiance/xbase/Array.js:986:34)
    at Function.getMultiverses (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:121:14)
    at next (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:51:22)
    at tiptoe (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:114:2)
    at retrieve (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:119:2)
    at /opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:104:3
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by Hologos** [comment] 2017-10-30 20:03
If you check the json files for core sets, the property foreignNames is included since 7ED onwards. I checked the git history of json files and it is missing since 2015. It seems like it is caused by a change in a code but I couldn't find what caused it.

**Comment by ZeldaZach** [comment] 2018-10-04 21:06
Addressed in V4 :)

**Closed by ZeldaZach** 2018-10-04 21:06 UTC
Labels: bug, help wanted
