### ISSUE TITLE
Multi-language card texts for foreign sets

### ISSUE THREAD

**Issue by aimadtakhtoukh** [mtgjson/mtgjson#238] opened 2016-09-30 09:15 UTC
Hello!

I've been using your data to create a yet-to-be-released application to query cards. The english part works like a charm, but as I'm French, I'd like to be able to access French card texts as well as names. Eventually, localization is also in my scope, which means reaching other languages... Are there still evolutions needed on the multi-lang branch?

Thanks for your attention.

**Comment by fenhl** [comment] 2018-02-19 14:09
Closing as duplicate of #456.

**Closed by fenhl** 2018-02-19 14:09 UTC
Labels: duplicate, question
