### ISSUE TITLE
Bug: Promo Sultai Ascendancy Misnamed

### ISSUE THREAD

**Issue by dlras2** [mtgjson/mtgjson#469] opened 2017-09-29 12:52 UTC
The promo card in CP2 has the `name` and `imageName` "Sultai Ascendacy" without the 'n'.

**Comment by tooomm** [comment] 2017-10-12 10:31
duplicate of https://github.com/mtgjson/mtgjson/issues/437

**Closed** 2017-10-12 10:32 UTC
Labels: duplicate
