### ISSUE TITLE
Mudhole missing from card list

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#378] opened 2017-07-09 05:44 UTC
Mudhole appears to be missing from the list of cards. I have no idea why it's specifically this one. If someone knows where I can find a list of all cards that doesn't get its info from MTGJSON, I can check for others.

**Comment by fenhl** [comment] 2017-07-10 19:52
Closing as duplicate of #382 which has a more extensive list of missing cards.

**Closed by fenhl** 2017-07-10 19:52 UTC
Labels: bug
