### ISSUE TITLE
Split cards in HOU update are screwed up.

### ISSUE THREAD

**Issue by Grim-the-Reaper** [mtgjson/mtgjson#374] opened 2017-07-09 01:35 UTC
They show up as First Half // First Half.
The mana cost and rules text are also the same twice.
The color only mentions the left half, but no //

Fuse is on both halves (not sure if that's normal)

**Comment by Garbee** [comment] 2017-07-09 02:07
This should probably get merged up into #375 which covers the same ground and then some.

**Comment by fenhl** [comment] 2017-07-10 06:58
Closing as duplicate of #375. And yes, fuse being on both halves is correct.

**Closed by fenhl** 2017-07-10 06:58 UTC
