### ISSUE TITLE
Clash Pack version of Sultai Ascendancy is named Sultai Ascendacy

### ISSUE THREAD

**Issue by jceddy** [mtgjson/mtgjson#506] opened 2017-11-25 13:04 UTC
I noticed this was wrong in Gatherer and has propagated to a lot of other sites. If we manually fix it in mtgjson will the bad spelling overwrite it again on the next set update or something?

**Comment by fenhl** [comment] 2017-11-25 13:35
Closing as duplicate of #437.

**Closed by fenhl** 2017-11-25 13:35 UTC
Labels: duplicate
