### ISSUE TITLE
include additional general information in file

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#347] opened 2017-05-16 19:53 UTC
It would be nice to have e.g. a `date of creation` and `version number` information in the json files.
For automated update checking reasons or just knowing which version of the file you are actually using, or if there are new versions/updates available! Same for troubleshooting and easy identification of outdated versions for example...

Would allow for easy and quick checks against http://mtgjson.com/json/version.json or http://mtgjson.com/json/changelog.json for example.

Right now the first level starts with real data already, so this structural change would be better something for [mtgjson v4](https://github.com/mtgjson/mtgjson4)?

**Comment by fenhl** [comment] 2017-08-17 12:56
Closing as duplicate of mtgjson/mtgjson4#53.

**Closed by fenhl** 2017-08-17 12:56 UTC
Labels: duplicate, feature, wontfix
