### ISSUE TITLE
Cards number 175 often go missing

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#949] opened 2022-06-15 11:16 UTC
So mtgjson very often drops some cards, only to get them back next time it's published. It's been going like that for months. This time it's an unusually long list.

Here's the latest one:

```
4ED - conflicting update
  CARD DEL: 175 Ali Baba
AER - conflicting update
  CARD DEL: 173 Renegade Map
  CARD DEL: 174 Reservoir Walker
  CARD DEL: 175 Scrap Trawler
KLD - conflicting update
  CARD DEL: 173 Wild Wanderer
  CARD DEL: 174 Wildest Dreams
  CARD DEL: 175 Wily Bandar
MID - conflicting update
  CARD DEL: 172 Briarbridge Tracker
MIR - conflicting update
  CARD DEL: 175 Flame Elemental
ODY - conflicting update
  CARD DEL: 175 Barbarian Lunatic
OGW - conflicting update
  CARD DEL: 175 Needle Spires
POR - conflicting update
  CARD DEL: 161 Charging Rhino
  CARD DEL: 162 Deep Wood
  CARD DEL: 163 Elite Cat Warrior
  CARD DEL: 164 Elven Cache
  CARD DEL: 164s Elven Cache
```

So what's extremely notable is that usually card 175 is dropped, or one just before it.

So this looks like most likely some error with pagination (or much less likely throttling). It's hard to come up with many scenarios where card 175 is specifically missing so many times, but no other cards.

**Comment by ZeldaZach** [comment] 2022-06-15 17:29
Dupe of https://github.com/mtgjson/mtgjson/issues/948, but yeah it's an upstream pagination issue that I'm working on with them. Hopefully we can get this finalized soon, and if not I can come up with workaround on my end

**Closed as completed by ZeldaZach** 2022-06-15 17:29 UTC
