### ISSUE TITLE
"Placed" syntax deprecated

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#335] opened 2017-05-07 07:33 UTC
`placed` is no longer used for describing the act of adding counters to objects. It is only `put`. (Gatherer confirms the change; Hardened Scales is an excellent example.)

The following cards use `placed` incorrectly (should be `put`):

Corpsejack Menace
Fathom Mage
Hardened Scales
Flourishing Defenses
Tatterkite
Melira's Keepers
Melira, Sylvok Outcast
Primal Vigor
Bloodcrazed Hoplite
Enduring Scalelord

**Comment by silasary** [comment] 2017-05-14 14:24
Duplicate of #327, which was fixed as part of #328.

**Closed** 2017-07-15 20:44 UTC
