### ISSUE TITLE
Data for cards is incomplete or wrong

### ISSUE THREAD

**Issue by LKay** [mtgjson/mtgjson#714] opened 2020-11-11 04:37 UTC
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against

Version: 5.0.1+20201109

### Issue with missing data

Card variations are missing data, such as translations, multiverseId etc. even if the card variations exist.

For example a card extended art variation of the `Agadeem's Awakening // Agadeem, the Undercrypt` from `ZNR` set. The card exists in the Gatherer, yet missing proper ids in the Json file:

- https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=495619

Also this card is missinf translation variants even if they are available: https://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=495619

### Issue with wrong data

The wrong data and multiverseId is set for "meld" or double faced cards. Both sides of the card point to the same multiverseIs, which is front face of the card.

**Comment by ZeldaZach** [comment] 2021-02-18 02:00
Yeahhh dupe of #718 (I know this is older, but I saw that one first )

**Closed as completed by ZeldaZach** 2021-02-18 02:00 UTC
