### ISSUE TITLE
Welcome Deck 2016 is missing "translations" for set name

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#172] opened 2016-05-31 16:04 UTC
http://mtgjson.com/json/W16.json

**Comment by gwax** [comment] 2016-06-03 02:13
"releaseDate" issue is a duplicate of #148 which has been solved and closed in master but not yet released.

"type" is, as yet, not resolved.

**Comment by tooomm** [comment] 2016-06-03 17:56
You are right. https://github.com/lsmoura/mtgjson/commit/005058fe7 fixed the "release" date at least in the repo (change is not live yet!).

While checking in detail again I saw that "translations" of the set name are missing as well, but it might be that there are just none...

**Comment by tooomm** [comment] 2016-06-13 11:01
"type" was also a duplicate and got fixed: https://github.com/lsmoura/mtgjson/issues/159
Type and release date are also live now!

Don't know if there are any translations available like for [SOI](https://raw.githubusercontent.com/lsmoura/mtgjson/41ce033eed96c2bb4a2723f6e17e79e10ac6359f/json/SOI.json) :
> "translations": {
    "de": "Schatten über Innistrad",
    "fr": "Ténèbres sur Innistrad",
    "it": "Ombre su Innistrad",
    "es": "Sombras sobre Innistrad",
    "pt": "Sombras em Innistrad",
    "jp": "イニストラードを覆う影",
    "cn": "依尼翠暗影",
    "ru": "Тени над Иннистрадом",
    "ko": "이니스트라드에 드리운 그림자"

**Comment by lsmoura** [comment] 2016-06-13 11:17
I'm trying to find the translation names.

I see that there are many translations for the W16 cards on gatherer, but I'm having a hard time finding official information about this deck like [this one for EMA](http://magic.wizards.com/en/node/985351).

**Comment by ZeldaZach** [comment] 2018-10-04 20:57
Addressed in V4

**Closed by ZeldaZach** 2018-10-04 20:57 UTC
