### ISSUE TITLE
Card duplicates in 10E in AllSets.json

### ISSUE THREAD

**Issue by ivodopyanov** [mtgjson/mtgjson#135] opened 2018-11-22 06:10 UTC
Each card is followed by its duplicate for 10E set in AllSets.json.
Those duplicates has no 'multiverseId' field and their 'number' field ends with a star symbol.
Is this intended?

**Comment by ZeldaZach** [comment] 2018-11-22 06:34
Duplicate of #116

**Closed as completed by ZeldaZach** 2018-11-22 06:34 UTC
Labels: Duplicate
