### ISSUE TITLE
Missing Foreign Limited & Unlimited Edition

### ISSUE THREAD

**Issue by sebastiandine** [mtgjson/mtgjson#579] opened 2018-05-11 18:06 UTC
Europe specific sets like **Foreign Black and White Bordered** as well as **Renaissance**, are missing.

**Comment by silasary** [comment] 2018-05-15 03:58
Duplicate of #295

**Comment by tooomm** [comment] 2018-05-15 07:06
Is it @silasary?
Doesn't #295 only speaks about renaissance?

**Comment by sebastiandine** [comment] 2018-05-15 08:29
Correct, it seems like there is no extra issue about foreign black and white bordered.

**Comment by sebastiandine** [comment] 2018-05-15 18:03
done

**Comment by MarkMYoung** [comment] 2018-05-17 16:05
While the topic of missing foreign sets is being discussed, Salvat 2005 and Salvat 2011 are also missing (https://mtg.gamepedia.com/Salvat).  The cards were printed in Spanish, French, and Italian, but I'm not sure about the exact breakdown by set or card even.  I have over 20 cards from Salvat 2005 but cannot inventory them because the app. I use references this project.

**Comment by ancestral** [comment] 2018-06-03 05:08
@MarkMYoung That’s not a set, though. Wouldn’t that be promotional? MTGJSON hasn’t cared about most promo releases.

**Comment by fenhl** [comment] 2018-06-03 05:13
Missing promos are a bug, not a feature.

**Comment by ancestral** [comment] 2018-06-03 05:14
Does that mean you want to also include Sewers of Estark and Shichifukujin Dragon?

**Comment by fenhl** [comment] 2018-06-03 05:16
Sure, those are real cards legal in Vintage.

**Comment by ZeldaZach** [comment] 2018-06-03 05:16
I want any and all cards ever printed included, so yes @ancestral

**Comment by ancestral** [comment] 2018-06-03 05:20
Well, the dragon is definitely not legal, as aren’t quite a few other celebration cards.

There are also digital cards from that Magic Shandalar game. But I think the place to draw the line is if the card name is on Gatherer. (I’m still not sold about worrying about sets not in Gatherer though. Sewers is listed as a promo in Gatherer, but Carrion Rats isn’t.)

**Comment by ZeldaZach** [comment] 2018-10-04 21:17
Addressed on V4

**Closed by ZeldaZach** 2018-10-04 21:17 UTC
Labels: feature
